# Test any changes here to see the impact - https://config.travis-ci.com/explore
dist: bionic
language: php

php:
  - 7.4
  - 8.0
  - 8.1.0

env:
  global:
    - setup=basic
    - xdebug=false
  jobs:
    - LARAVEL_VERSION=8.*

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ $xdebug = 'true' ]] ; then phpenv config-rm xdebug.ini; fi
  - composer self-update --2

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable --prefer-lowest; fi

before_script:
  - travis_retry composer install --prefer-source --no-interaction
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "illuminate/routing:${LARAVEL_VERSION}" --no-update; fi;
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "illuminate/support:${LARAVEL_VERSION}" --no-update; fi;
  - composer update

script:
  - vendor/bin/phpunit
