name: CI Tests

on:
  pull_request:
  push:
    branches:
      - master
      - v*

jobs:
  tests:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        stability: [prefer-stable]
        versions: [ { php: 8.2, laravel: 10 }, { php: 8.3, laravel: 10 }, { php: 8.4, laravel: 10 },  { php: 8.2, laravel: 11 }, { php: 8.3, laravel: 11 }, { php: 8.4, laravel: 11 }, { php: 8.2, laravel: 12 }, { php: 8.3, laravel: 12 }, { php: 8.4, laravel: 12 } ]

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.versions.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          # todo: Add
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=^${{ matrix.versions.laravel }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Run phpunit tests
        run: composer test
